export const carData = [
  {
    title: "Light Legend",
    name: "Honda NSX",
    engineType: "3.0L V6 DOHC VTEC",
    boost: "N/A",
    horsePower: "274 HP",
    topSpeed: "270 km/h",
    description:
      "Co-developed with Ayrton Senna, the NSX was the first production car with an all-aluminum body. Designed to rival Ferrari, it offered supercar performance with Honda reliability.",
    specs: {
      production: "1990–2005",
      torque: "285 Nm @ 5400 RPM",
      drivetrain: "RWD",
      transmission: "5-speed manual / 4-speed automatic",
      acceleration: "0-100 km/h in ~5.5 s",
      weight: "1350 kg",
      suspension: "Double wishbone (front and rear)",
      brakes: "Ventilated disc brakes",
    },
  },
  {
    title: "Godzilla R34",
    name: "Nissan Skyline R34 GT-R",
    engineType: "2.6L Inline-6 Twin-Turbo (RB26DETT)",
    boost: "Twin-Turbo",
    horsePower: "280 HP (official) / ~320 HP (real)",
    topSpeed: "290 km/h (derestricted)",
    description:
      "Dubbed 'Godzilla', the R34 GT-R featured an advanced Multi-Function Display (MFD) showing real-time engine and turbo data, and had an ATTESA E-TS Pro AWD system.",
    specs: {
      production: "1999–2002",
      torque: "392 Nm @ 4400 RPM",
      drivetrain: "AWD (ATTESA E-TS Pro)",
      transmission: "6-speed manual (Getrag)",
      acceleration: "0-100 km/h in ~4.9 s",
      weight: "1560 kg",
      suspension: "Multi-link (front and rear)",
      brakes: "Brembo ventilated discs",
    },
  },
  {
    title: "Boost Beast",
    name: "Toyota Supra MK4 (A80)",
    engineType: "3.0L Inline-6 Twin-Turbo (2JZ-GTE)",
    boost: "Twin-Turbo",
    horsePower: "280 HP (official) / ~320-330 HP (real)",
    topSpeed: "285 km/h (derestricted)",
    description:
      "Powered by the legendary 2JZ-GTE twin-turbo engine, the Supra became an ultimate tuning icon, often exceeding 1000 HP with modifications.",
    specs: {
      production: "1993–2002",
      torque: "431 Nm @ 4000 RPM",
      drivetrain: "RWD",
      transmission: "6-speed manual (Getrag V160) / 4-speed automatic",
      acceleration: "0-100 km/h in ~4.9 s",
      weight: "1560 kg",
      suspension: "Double wishbone (front and rear)",
      brakes: "Ventilated discs",
    },
  },
  {
    title: "Rotary Master",
    name: "Mazda RX-7 (FD3S)",
    engineType: "1.3L Twin-Rotor Twin-Turbo (13B-REW)",
    boost: "Twin-Turbo",
    horsePower: "280 HP",
    topSpeed: "250 km/h",
    description:
      "The RX-7’s lightweight rotary engine and perfect 50:50 weight distribution made it one of the best-handling sports cars ever built.",
    specs: {
      production: "1992–2002",
      torque: "314 Nm @ 5000 RPM",
      drivetrain: "RWD",
      transmission: "5-speed manual / 4-speed automatic",
      acceleration: "0-100 km/h in ~5.1 s",
      weight: "1270 kg",
      suspension: "Double wishbone (front and rear)",
      brakes: "Ventilated discs",
    },
  },
  {
    title: "Drift Icon",
    name: "Nissan 180SX (S13)",
    engineType: "1.8L Inline-4 Turbo (CA18DET) / 2.0L Inline-4 Turbo (SR20DET)",
    boost: "Turbocharged",
    horsePower: "170 HP (CA18DET) / 205 HP (SR20DET)",
    topSpeed: "225 km/h",
    description:
      "A JDM drift legend, the 180SX came with pop-up headlights and was powered by the CA18DET or SR20DET turbocharged engines. Known for its lightweight chassis and RWD setup.",
    specs: {
      production: "1989–1998",
      torque: "226 Nm (CA18DET) / 274 Nm (SR20DET)",
      drivetrain: "RWD",
      transmission: "5-speed manual / 4-speed automatic",
      acceleration: "0-100 km/h in ~6.5 s",
      weight: "1220 kg",
      suspension: "MacPherson strut (front), multi-link (rear)",
      brakes: "Ventilated discs",
    },
  },
];
